- name: Configure application
  hosts: all
  become: true
  become_method: sudo
  vars:
      repository_url: https://github.com/flyd0g/flask-hello-world.git
      repository_path: /home/vagrant/flask-hello-world

  tasks:
    - name: Install packages
      apt: update_cache=yes name={{ item }} state=present
      with_items:
        - git
        - python3-pip
        - nginx

    - name: Clone repository
      git: repo='{{ repository_url }}' dest='{{ repository_path }}'

    - name: Install requirements
      pip: requirements='{{ repository_path }}/requirements.txt'

    - name: Configure the service
      template: src=hello-world.service dest=/etc/systemd/system/hello-world.service mode=755
      notify:
          - reload systemctl

    - name: Make sure our server is running
      service: name=hello-world.service state=started enabled=yes

    - name: Copy nginx site
      template: src=hello-world dest=/etc/nginx/sites-enabled/hello-world
      notify:
          - restart nginx

    - name: Remove any default sites
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify:
        - restart nginx

    - name: Make sure nginx is running
      service: name=nginx state=started enabled=yes

  handlers:
    - name: reload systemctl
      command: systemctl daemon-reload

    - name: restart nginx
      service: name=nginx state=restarted
